# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    # https://docs.fastlane.tools/actions/setup_ci/
    setup_ci if ENV["CI"]
    
    # https://docs.fastlane.tools/actions/sync_code_signing/
    sync_code_signing()
    sync_code_signing(type: "appstore")
    
    # https://docs.fastlane.tools/actions/build_app/
    build_app(scheme: "FastlaneDemo", include_bitcode: true)

    # https://docs.fastlane.tools/actions/app_store_connect_api_key/
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: ENV["API_KEY"]
    )

    # https://docs.fastlane.tools/actions/upload_to_testflight/
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)
  end

  lane :tests do
    # https://docs.fastlane.tools/actions/run_tests/
    run_tests(scheme: "FastlaneDemoTests")
  end
end
