# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :beta do
    # https://docs.fastlane.tools/actions/setup_ci/
    setup_ci if ENV["CI"]
    
    # https://docs.fastlane.tools/actions/sync_code_signing/
    sync_code_signing()
    sync_code_signing(type: "appstore")

    carthage(
      platform: "iOS",
      cache_builds: true,
      use_xcframeworks: true
    )

    # https://docs.fastlane.tools/actions/app_store_connect_api_key/
    api_key = app_store_connect_api_key(
      key_id: ENV["API_KEY_ID"],
      issuer_id: ENV["API_ISSUER_ID"],
      key_content: ENV["API_KEY"]
    )

    # https://docs.fastlane.tools/actions/latest_testflight_build_number/#latest_testflight_build_number
    # build_number = latest_testflight_build_number(api_key: api_key) + 1

    # https://docs.fastlane.tools/actions/increment_build_number/#increment_build_number
    build_number = Time.now.to_i
    increment_build_number(build_number: build_number)
    puts("build number => #{build_number}")

    # https://docs.fastlane.tools/actions/build_app/
    build_app(scheme: "FastlaneDemo", include_bitcode: false)

    # https://docs.fastlane.tools/actions/upload_to_testflight/
    upload_to_testflight(skip_waiting_for_build_processing: true, api_key: api_key)

    # https://github.com/getsentry/sentry-fastlane-plugin#sentry-actions
    # https://docs.sentry.io/platforms/apple/guides/macos/dsym/
    # sentry_upload_dsym(
    #   auth_token: ENV["SENTRY_TOKEN"],
    #   org_slug: ENV["SENTRY_ORG"],
    #   project_slug: ENV["SENTRY_PROJECT"]
    # )
  end

  lane :sentry_sync_dsyms do
    # https://docs.sentry.io/platforms/apple/guides/macos/dsym/
    download_dsyms()

    # https://github.com/getsentry/sentry-fastlane-plugin#sentry-actions
    # https://docs.sentry.io/platforms/apple/guides/macos/dsym/
    sentry_upload_dsym(
      auth_token: ENV["SENTRY_TOKEN"],
      org_slug: ENV["SENTRY_ORG"],
      project_slug: ENV["SENTRY_PROJECT"]
    )
  end

  lane :tests do
    # https://docs.fastlane.tools/actions/run_tests/
    run_tests(scheme: "FastlaneDemoTests")
  end
end
