name: beta
on:
  push:
    tags:
      - beta/v*

jobs:
  testflight:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2

      - name: install sentry-cli
        run: brew install getsentry/tools/sentry-cli

      - name: cache carthage
        uses: actions/cache@v2
        with:
          path: Carthage
          key: ${{ runner.os }}-carthage-${{ hashFiles('**/Cartfile.resolved') }}
          restore-keys: ${{ runner.os }}-carthage-

      - name: cache spm
        uses: actions/cache@v2
        with:
          # path: .build
          path: /Users/runner/Library/Developer/Xcode/DerivedData/**/SourcePackages/checkouts
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: upload
        run: fastlane beta
        env:
          # https://docs.fastlane.tools/codesigning/getting-started/#using-match
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_GIT_URL: ${{ secrets.MATCH_GIT_URL }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ secrets.MATCH_GIT_BASIC_AUTHORIZATION }}
          # appstoreconnect.apple.com
          APP_BUNDLE_ID: ${{ secrets.APP_BUNDLE_ID }}
          APP_STORE_CONNECT_TEAM_ID: ${{ secrets.APP_STORE_CONNECT_TEAM_ID }}
          # developer.apple.com
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}
          # https://docs.fastlane.tools/app-store-connect-api/
          API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          API_KEY: ${{ secrets.API_KEY }}
          # sentry
          SENTRY_TOKEN: ${{ secrets.SENTRY_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
